input:

  table: 'lib_product_data'
  fields: "id, product, alias_name, scope, sub_scope, tags, icon, ticket, business, `desc`, born_date, region, city, company, is_del, is_choice, invest_id, update_time"

  # mysql://user:$w$alZCMJf6bwX5l@101.200.32.86:3306/data
  mysql:
    database: data
    user: user
    password: '$w$alZCMJf6bwX5l'
    host: '101.200.32.86'
    port: 3306

  size: 2000

output:
  index: 'product-20200909'
  stdout": false
